In [11]:
import pandas as pd
import json
import ast
import warnings
from ast import literal_eval as le
import plotly.express as px

warnings.filterwarnings("ignore")
import requests
import pandas as pd
import urlexpander


def unshorten(url):
    if "http" not in url:
        url = "http://" + url

    try:
        short = urlexpander.expand(url)
    except:
        short = url

    if "_ERROR__" in short:
        return url
    else:
        return short


def one_url_df(df, column="n_urls", urls="urls"):
    df = df[df[column] == 1]
    df[urls] = df[urls].apply(lambda x: x[0])
    return df


def more_url_df(df, interaction, n="n_urls", urls="urls"):
    df = df[df[n] > 1]
    temp = []
    for i in df.iterrows():
        row = i[1].to_dict()
        for url in row[urls]:
            temp.append((url, row[interaction], row[n]))
    return (
        pd.DataFrame(temp)
        .drop_duplicates()
        .rename(columns={0: urls, 1: interaction, 2: n})
    )

def plot(df, x):
    fig = px.histogram(df, x)
    fig.show();
    
def fix(df):
    df["urls"] = df["urls"].apply(lambda x: le(x))
    df["n_urls"] = df["urls"].apply(lambda x: len(x))

def un(df):
    df["urls"] = df["urls"].apply(lambda x: unshorten(x))
    
def sort(df, column):
    df.sort_values(column, inplace=True, ascending=False)

# Top Shared

## Top Interacted

In [12]:
top_4_months = pd.read_csv("../Top_Interacted_Data/instagram_4_months.csv").drop(columns= "Unnamed: 0")
top_4_months.rename(columns={"media_id": "id/url"}, inplace=True)
top_4_months.head(5)

,shared_url,id/url,text,n_likes,n_replies,total,url_id
0,https://www.hollywoodreporter.com/news/marvel-...,2.546105e+18,@wolf_sazen the story broke August 2015 \n\nht...,827.0,NaN,827.0,instagram_comments_4_months_0
1,www.change.org/p/walt-disney-we-want-johnny-de...,2.515803e+18,@pia_kusianovich www.change.org/p/walt-disney-...,424.0,NaN,424.0,instagram_comments_4_months_1
2,https://www.google.com.br/amp/s/amp.news.com.a...,2.538091e+18,"@isgaovieira Bem, acho que voce não deve ter l...",88.0,NaN,88.0,instagram_comments_4_months_2
3,http://chng.it/9fvfm2mSb4,2.515803e+18,@feliperailen15._ http://chng.it/9fvfm2mSb4,69.0,NaN,69.0,instagram_comments_4_months_3
4,http://chng.it/r7wxtqT8N9,2.515803e+18,@feliperailen15._ http://chng.it/r7wxtqT8N9,69.0,NaN,69.0,instagram_comments_4_months_4

In [13]:
top_dec = pd.read_csv("../Top_Interacted_Data/instagram_dec.csv").drop(columns= "Unnamed: 0")
top_dec.rename(columns={"media_id": "id/url"}, inplace=True)
top_dec.head(5)

,shared_url,id/url,text,n_likes,n_replies,total,url_id
0,http://chng.it/6FQKFDHkLS,2.455510e+18,@lenynacarrasco http://chng.it/6FQKFDHkLS,2044.0,NaN,2044.0,instagram_comments_dec_0
1,http://chng.it/6FQKFDHkLS,2.455510e+18,@_.pl3tor1co._ http://chng.it/6FQKFDHkLS,705.0,NaN,705.0,instagram_comments_dec_1
2,http://chng.it/cRRfCKcsbm,2.455510e+18,@samurai_maca http://chng.it/cRRfCKcsbm,537.0,NaN,537.0,instagram_comments_dec_2
3,http://chng.it/6FQKFDHkLS,2.455510e+18,@__senpaaii_ http://chng.it/6FQKFDHkLS,430.0,NaN,430.0,instagram_comments_dec_3
4,http://chng.it/6FQKFDHkLS,2.455510e+18,@elmuerto_inactivo http://chng.it/6FQKFDHkLS,372.0,NaN,372.0,instagram_comments_dec_4

## Shared URLs

In [14]:
shared_4_months = pd.read_csv("../URLs_Data/df_shared_4_months.csv")
shared_4_months.fillna("{1}", inplace=True)
shared_4_months["n_urls"] = shared_4_months["n_urls"].apply(lambda x: le(x))
shared_4_months.rename(columns={"shared_link": "shared_url"}, inplace=True)
shared_4_months.head(5)

,shared_url,n_shared,from_n_users,users,n_urls,platform,from
0,https://www.change.org/p/walt-disney-back-john...,6,1,"(1181480925,)",{1},change,petition_comment
1,https://www.change.org/p/me-johnny-depp-as-jac...,3,1,"(1181480925,)",{1},change,petition_comment
2,https://www.change.org/p/%D0%BC%D0%B8%D0%B4-%D...,2,1,{1179297829},{4},change,petition_comment
3,https://www.change.org/p/loma-vista-recordings...,2,1,{1179297829},{4},change,petition_comment
4,https://www.change.org/p/warner-brothers-keep-...,2,1,{1198070350},{2},change,petition_comment

In [15]:
shared_dec = pd.read_csv("../URLs_Data/df_shared_dec.csv")
shared_dec.rename(columns={"shared_link": "shared_url"}, inplace=True)
shared_dec.head(5)

,shared_url,n_shared,from_n_users,users,n_urls,platform,from
0,https://www.documentcloud.org/documents/583586...,16,4,"{948054032, 1129808400, 1136503772, 1081693988}","{8, 10, 4}",change,petition_comment
1,https://www.latimes.com/entertainment/gossip/l...,16,4,"{948054032, 1129808400, 1136503772, 1081693988}","{8, 10, 4}",change,petition_comment
2,https://www.truehollywoodtalk.com/amber-heards...,10,2,"{1136503772, 1081693988}","{8, 10, 2}",change,petition_comment
3,https://www.youtube.com/channel/UCjKNc-woAlnxt...,8,2,"{1136503772, 1081693988}","{8, 10}",change,petition_comment
4,https://www.change.org/p/we-support-amber-hear...,6,1,{1081693988},{10},change,petition_comment

# 4

### Top shared instagram

In [16]:
shared_4_months_instagram = shared_4_months[shared_4_months.platform == "instagram"]
shared_4_months_instagram

,shared_url,n_shared,from_n_users,users,n_urls,platform,from
10,https://youtu.be/uretrfMA-Io,17,8,"(8576468286.0, 8993278596.0, 6355289605.0, 292...",{1},instagram,comment
11,http://chng.it/9fvfm2mSb4,17,1,"(2066707406.0,)",{1},instagram,comment
12,www.change.org/p/walt-disney-we-want-johnny-de...,10,2,"(3034584675.0, 40838726015.0)",{1},instagram,comment
13,https://rojakdaily.com/entertainment/article/1...,6,1,"(2226100100.0,)",{1},instagram,comment
14,https://www.thesun.co.uk/news/uknews/12087519/...,6,1,"(7362926991.0,)",{1},instagram,comment
...,...,...,...,...,...,...,...
241,https://youtu.be/eeoc35OZnr8,1,1,{15794220150.0},{6},instagram,comment
242,https://youtu.be/ykPgjXNwwkE,1,1,"(15794220150.0,)",{1},instagram,comment
243,https://youtu.be/vPrYKz9DZ6E,1,1,{15794220150.0},{6},instagram,comment
244,https://youtu.be/cvWWEwM-Yz8,1,1,{15794220150.0},{6},instagram,comment
245,https://youtu.be/jYF392_nfaA,1,1,{15794220150.0},{5},instagram,comment

In [17]:
saving = "../Top_Shared_Data/"

In [18]:
top_shared_instagram_4_months = pd.merge(
    shared_4_months_instagram, top_4_months, how="inner"
)
top_shared_instagram_4_months = top_shared_instagram_4_months.sort_values(
    "total", ascending=False
).reset_index(drop=True)

In [19]:
top_shared_instagram_4_months.to_csv(saving + "top_shared_instagram_4_months.csv")

In [20]:
top_shared_instagram_4_months

,shared_url,n_shared,from_n_users,users,n_urls,platform,from,id/url,text,n_likes,n_replies,total,url_id
0,https://www.hollywoodreporter.com/news/marvel-...,1,1,"(26267867.0,)",{1},instagram,comment,2.546105e+18,@wolf_sazen the story broke August 2015 \n\nht...,827.0,NaN,827.0,instagram_comments_4_months_0
1,www.change.org/p/walt-disney-we-want-johnny-de...,10,2,"(3034584675.0, 40838726015.0)",{1},instagram,comment,2.515803e+18,@pia_kusianovich www.change.org/p/walt-disney-...,424.0,NaN,424.0,instagram_comments_4_months_1
2,https://www.google.com.br/amp/s/amp.news.com.a...,3,1,"(2887462385.0,)",{1},instagram,comment,2.538091e+18,"@isgaovieira Bem, acho que voce não deve ter l...",88.0,NaN,88.0,instagram_comments_4_months_2
3,http://chng.it/r7wxtqT8N9,2,1,"(7571699105.0,)",{1},instagram,comment,2.515803e+18,@feliperailen15._ http://chng.it/r7wxtqT8N9,69.0,NaN,69.0,instagram_comments_4_months_4
4,http://chng.it/9fvfm2mSb4,17,1,"(2066707406.0,)",{1},instagram,comment,2.515803e+18,@feliperailen15._ http://chng.it/9fvfm2mSb4,69.0,NaN,69.0,instagram_comments_4_months_3
5,https://rojakdaily.com/entertainment/article/1...,6,1,"(2226100100.0,)",{1},instagram,comment,2.517016e+18,@yuliannagonca https://rojakdaily.com/entertai...,61.0,NaN,61.0,instagram_comments_4_months_5
6,https://www.google.com.mx/amp/s/www.businessin...,1,1,"(1733469043.0,)",{1},instagram,comment,2.517075e+18,@axelfaz0304 aquí está la fuente https://www.g...,50.0,NaN,50.0,instagram_comments_4_months_6
7,https://youtu.be/uretrfMA-Io,17,8,"(8576468286.0, 8993278596.0, 6355289605.0, 292...",{1},instagram,comment,2.479190e+18,@mr_fenix_23 ( YouTube channel name : Access )...,42.0,NaN,42.0,instagram_comments_4_months_8
8,https://youtu.be/uretrfMA-Io,17,8,"(8576468286.0, 8993278596.0, 6355289605.0, 292...",{1},instagram,comment,2.479190e+18,@mr_fenix_23 ( YouTube channel name : Access )...,42.0,NaN,42.0,instagram_comments_4_months_7
9,https://youtu.be/uretrfMA-Io,17,8,"(8576468286.0, 8993278596.0, 6355289605.0, 292...",{1},instagram,comment,2.479190e+18,@mr_fenix_23 ( YouTube channel name : Access )...,42.0,NaN,42.0,instagram_comments_4_months_9
10,http://chng.it/w8RnpBfD2f,1,1,"(41433524061.0,)",{1},instagram,comment,2.515803e+18,@seba.ignaciio_nr http://chng.it/w8RnpBfD2f,33.0,NaN,33.0,instagram_comments_4_months_10
11,www.change.org/p/walt-disney-we-want-johnny-de...,10,2,"(3034584675.0, 40838726015.0)",{1},instagram,comment,2.515803e+18,@pinoshrekista www.change.org/p/walt-disney-we...,30.0,NaN,30.0,instagram_comments_4_months_11
12,www.change.org/p/walt-disney-we-want-johnny-de...,10,2,"(3034584675.0, 40838726015.0)",{1},instagram,comment,2.515803e+18,@pinoshrekista www.change.org/p/walt-disney-we...,30.0,NaN,30.0,instagram_comments_4_months_12
13,www.change.org/p/walt-disney-we-want-johnny-de...,10,2,"(3034584675.0, 40838726015.0)",{1},instagram,comment,2.515803e+18,@pinoshrekista www.change.org/p/walt-disney-we...,30.0,NaN,30.0,instagram_comments_4_months_13
14,www.change.org/p/walt-disney-we-want-johnny-de...,10,2,"(3034584675.0, 40838726015.0)",{1},instagram,comment,2.515803e+18,@pinoshrekista www.change.org/p/walt-disney-we...,23.0,NaN,23.0,instagram_comments_4_months_14
15,www.change.org/p/walt-disney-we-want-johnny-de...,10,2,"(3034584675.0, 40838726015.0)",{1},instagram,comment,2.515803e+18,@pinoshrekista www.change.org/p/walt-disney-we...,23.0,NaN,23.0,instagram_comments_4_months_15
16,www.change.org/p/walt-disney-we-want-johnny-de...,10,2,"(3034584675.0, 40838726015.0)",{1},instagram,comment,2.515803e+18,@pinoshrekista www.change.org/p/walt-disney-we...,23.0,NaN,23.0,instagram_comments_4_months_16
17,https://agenciadenoticias.ibge.gov.br/agencia-...,1,1,"(17373380465.0,)",{1},instagram,comment,2.481554e+18,@_rrogerr https://agenciadenoticias.ibge.gov.b...,23.0,NaN,23.0,instagram_comments_4_months_17
18,https://rojakdaily.com/entertainment/article/1...,6,1,"(2226100100.0,)",{1},instagram,comment,2.517016e+18,@dan_mgf https://rojakdaily.com/entertainment/...,22.0,NaN,22.0,instagram_comments_4_months_20
19,https://rojakdaily.com/entertainment/article/1...,6,1,"(2226100100.0,)",{1},instagram,comment,2.517016e+18,@dan_mgf https://rojakdaily.com/entertainment/...,22.0,NaN,22.0,instagram_comments_4_months_19
20,https://rojakdaily.com/entertainment/article/1...,6,1,"(2226100100.0,)",{1},instagram,comment,2.517016e+18,@dan_mgf https://rojakdaily.com/entertainment/...,22.0,NaN,22.0,instagram_comments_4_months_18
21,https://www.instagram.com/p/CLfHtgQA5De/?igshi...,1,1,"(6755183296.0,)",{1},instagram,comment,2.519745e+18,@serj_str https://www.instagram.com/p/CLfHtgQA...,17.0,NaN,17.0,instagram_comments_4_months_21
22,https://rojakdaily.com/entertainment/article/1...,6,1,"(2226100100.0,)",{1},instagram,comment,2.517016e+18,@natmargolla https://rojakdaily.com/entertainm...,16.0,NaN,16.0,instagram_comments_4_months_22
23,https://www.change.org/p/walt-disney-we-want-j...,3,3,"(12578338476.0, 492318828.0, 437045293.0)",{1},instagram,comment,2.515803e+18,https://www.change.org/p/walt-disney-we-want-j...,9.0,2.0,11.0,instagram_comments_4_months_23
24,http://chng.it/cz7n8nXPMS,1,1,"(8624506650.0,)",{1},instagram,comment,2.441013e+18,link : http://chng.it/cz7n8nXPMS,9.0,0.0,9.0,instagram_comments_4_months_24
25,www.change.org/p/walt-disney-we-want-johnny-de...,10,2,"(3034584675.0, 40838726015.0)",{1},instagram,comment,2.515803e+18,@martinabuguen0 www.change.org/p/walt-disney-w...,9.0,NaN,9.0,instagram_comments_4_months_28
26,http://chng.it/9fvfm2mSb4,17,1,"(2066707406.0,)",{1},instagram,comment,2.515803e+18,@flo.hernandezl http://chng.it/9fvfm2mSb4,9.0,NaN,9.0,instagram_comments_4_months_25
27,www.change.org/p/walt-disney-we-want-johnny-de...,10,2,"(3034584675.0, 40838726015.0)",{1},instagram,comment,2.515803e+18,@martinabuguen0 www.change.org/p/walt-disney-w...,9.0,NaN,9.0,instagram_comments_4_months_27
28,www.change.org/p/walt-disney-we-want-johnny-de...,10,2,"(3034584675.0, 40838726015.0)",{1},instagram,comment,2.515803e+18,@martinabuguen0 www.change.org/p/walt-disney-w...,9.0,NaN,9.0,instagram_comments_4_months_26
29,https://www.muz1.tv/events/7110,1,1,"(15484318697.0,)",{1},instagram,comment,2.482896e+18,https://www.muz1.tv/events/7110,8.0,NaN,8.0,instagram_comments_4_months_29
30,http://chng.it/9fvfm2mSb4,17,1,"(2066707406.0,)",{1},instagram,comment,2.515803e+18,@cataa.wh http://chng.it/9fvfm2mSb4,8.0,NaN,8.0,instagram_comments_4_months_30
31,https://rojakdaily.com/entertainment/article/1...,6,1,"(2226100100.0,)",{1},instagram,comment,2.517016e+18,@grigorimary https://rojakdaily.com/entertainm...,8.0,NaN,8.0,instagram_comments_4_months_31
32,https://youtu.be/uretrfMA-Io,17,8,"(8576468286.0, 8993278596.0, 6355289605.0, 292...",{1},instagram,comment,2.479190e+18,@legolive2005 https://youtu.be/uretrfMA-Io,7.0,NaN,7.0,instagram_comments_4_months_32
33,youtube.com/BeraniNggak,1,1,"(5588069473.0,)",{1},instagram,comment,2.482954e+18,"Lagi berduaan di rumah, tahu2 ada bayangan hit...",7.0,0.0,7.0,instagram_comments_4_months_33
34,https://youtu.be/uretrfMA-Io,17,8,"(8576468286.0, 8993278596.0, 6355289605.0, 292...",{1},instagram,comment,2.479190e+18,@mr_fenix_23 https://youtu.be/uretrfMA-Io here...,6.0,NaN,6.0,instagram_comments_4_months_35
35,https://www.cbr.com/powers-aquamans-trident-ne...,1,1,"(24626506295.0,)",{1},instagram,comment,2.415248e+18,@hesan_aminifard https://www.cbr.com/powers-aq...,6.0,NaN,6.0,instagram_comments_4_months_34
36,https://youtu.be/uretrfMA-Io,17,8,"(8576468286.0, 8993278596.0, 6355289605.0, 292...",{1},instagram,comment,2.479190e+18,@mr_fenix_23 https://youtu.be/uretrfMA-Io here...,6.0,NaN,6.0,instagram_comments_4_months_37
37,https://youtu.be/uretrfMA-Io,17,8,"(8576468286.0, 8993278596.0, 6355289605.0, 292...",{1},instagram,comment,2.479190e+18,@mr_fenix_23 https://youtu.be/uretrfMA-Io here...,6.0,NaN,6.0,instagram_comments_4_months_36
38,https://www.dailymail.co.uk/news/article-94749...,1,1,"(254610720.0,)",{1},instagram,comment,2.559848e+18,https://www.dailymail.co.uk/news/article-94749...,5.0,0.0,5.0,instagram_comments_4_months_38
39,https://www.change.org/p/the-walt-disney-compa...,1,1,"(1697980059.0,)",{1},instagram,comment,2.515803e+18,https://www.change.org/p/the-walt-disney-compa...,4.0,NaN,4.0,instagram_comments_4_months_39
40,http://chng.it/9fvfm2mSb4,17,1,"(2066707406.0,)",{1},instagram,comment,2.515803e+18,@connntreras http://chng.it/9fvfm2mSb4,4.0,NaN,4.0,instagram_comments_4_months_40
41,http://chng.it/9fvfm2mSb4,17,1,"(2066707406.0,)",{1},instagram,comment,2.515803e+18,http://chng.it/9fvfm2mSb4,2.0,1.0,3.0,instagram_comments_4_months_43
42,https://www.independent.co.uk/news/world/ameri...,1,1,"(7598916537.0,)",{1},instagram,comment,2.481203e+18,@zinxy8_r.i.p https://www.independent.co.uk/ne...,3.0,NaN,3.0,instagram_comments_4_months_41
43,http://chng.it/9fvfm2mSb4,17,1,"(2066707406.0,)",{1},instagram,comment,2.515803e+18,@tamara_alarconm http://chng.it/9fvfm2mSb4,3.0,NaN,3.0,instagram_comments_4_months_42

### Top shared youtube across all platforms

In [21]:
shared_4_months_instagram_all_platforms = pd.merge(
    shared_4_months, top_4_months, how="inner"
)
top_shared_instagram_4_months = top_shared_instagram_4_months.sort_values(
    "total", ascending=False
).reset_index(drop=True)

In [22]:
shared_4_months_instagram_all_platforms

,shared_url,n_shared,from_n_users,users,n_urls,platform,from,id/url,text,n_likes,n_replies,total,url_id
0,https://youtu.be/uretrfMA-Io,17,8,"(8576468286.0, 8993278596.0, 6355289605.0, 292...",{1},instagram,comment,2.479190e+18,@mr_fenix_23 ( YouTube channel name : Access )...,42.0,NaN,42.0,instagram_comments_4_months_7
1,https://youtu.be/uretrfMA-Io,17,8,"(8576468286.0, 8993278596.0, 6355289605.0, 292...",{1},instagram,comment,2.479190e+18,@mr_fenix_23 ( YouTube channel name : Access )...,42.0,NaN,42.0,instagram_comments_4_months_8
2,https://youtu.be/uretrfMA-Io,17,8,"(8576468286.0, 8993278596.0, 6355289605.0, 292...",{1},instagram,comment,2.479190e+18,@mr_fenix_23 ( YouTube channel name : Access )...,42.0,NaN,42.0,instagram_comments_4_months_9
3,https://youtu.be/uretrfMA-Io,17,8,"(8576468286.0, 8993278596.0, 6355289605.0, 292...",{1},instagram,comment,2.479190e+18,@legolive2005 https://youtu.be/uretrfMA-Io,7.0,NaN,7.0,instagram_comments_4_months_32
4,https://youtu.be/uretrfMA-Io,17,8,"(8576468286.0, 8993278596.0, 6355289605.0, 292...",{1},instagram,comment,2.479190e+18,@mr_fenix_23 https://youtu.be/uretrfMA-Io here...,6.0,NaN,6.0,instagram_comments_4_months_35
...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,https://www.change.org/p/the-walt-disney-compa...,94,14,"(8.253189287254671e+17, 1.268173251244626e+18,...",{1},twitter,tweet,2.515803e+18,https://www.change.org/p/the-walt-disney-compa...,4.0,NaN,4.0,instagram_comments_4_months_39
74,https://www.change.org/p/the-walt-disney-compa...,1,1,{1.32725448511522e+18},{2},twitter,tweet,2.515803e+18,https://www.change.org/p/the-walt-disney-compa...,4.0,NaN,4.0,instagram_comments_4_months_39
75,http://chng.it/w8RnpBfD2f,1,1,"(41433524061.0,)",{1},instagram,comment,2.515803e+18,@seba.ignaciio_nr http://chng.it/w8RnpBfD2f,33.0,NaN,33.0,instagram_comments_4_months_10
76,https://www.dailymail.co.uk/news/article-94749...,1,1,"(254610720.0,)",{1},instagram,comment,2.559848e+18,https://www.dailymail.co.uk/news/article-94749...,5.0,0.0,5.0,instagram_comments_4_months_38
77,https://www.hollywoodreporter.com/news/marvel-...,1,1,"(26267867.0,)",{1},instagram,comment,2.546105e+18,@wolf_sazen the story broke August 2015 \n\nht...,827.0,NaN,827.0,instagram_comments_4_months_0

In [23]:
shared_4_months_instagram_all_platforms.to_csv(saving + "top_shared_4_months_instagram_all_platforms.csv")

# DEC

### Top shared instagram

In [24]:
shared_dec_instagram = shared_dec[shared_dec.platform == "instagram"]
shared_dec_instagram

,shared_url,n_shared,from_n_users,users,n_urls,platform,from
11,https://www.change.org/p/dc-entertainment-remo...,26,7,"(30074255940.0, 3703701611.0, 2200653740.0, 56...",{1},instagram,comment
12,http://chng.it/6FQKFDHkLS,13,1,"(638630549.0,)",{1},instagram,comment
13,http://chng.it/Tx29y72h7Y,12,1,"(35924250393.0,)",{1},instagram,comment
14,http://chng.it/d4wSkC9HZs,12,2,"(37298049714.0, 286371978.0)",{1},instagram,comment
15,http://chng.it/DT7NQwK8kG,11,1,"(44298546457.0,)",{1},instagram,comment
...,...,...,...,...,...,...,...
171,https://youtu.be/TBuIGBCF9jc,1,1,{15794220150.0},{2},instagram,comment
172,https://youtu.be/Gq1i_4ajO3I,1,1,{15794220150.0},{5},instagram,comment
173,https://youtu.be/vOIMQaIdaRc,1,1,{15794220150.0},{5},instagram,comment
174,https://youtu.be/IzAO9A9GjgI,1,1,{15794220150.0},{2},instagram,comment
175,https://youtu.be/g2NDs8QsyDI,1,1,{15794220150.0},{5},instagram,comment

In [25]:
top_shared_instagram_dec = pd.merge(
    shared_dec_instagram, top_dec, how="inner"
)
top_shared_instagram_dec = top_shared_instagram_dec.sort_values(
    "total", ascending=False
).reset_index(drop=True)

In [26]:
top_shared_instagram_dec

,shared_url,n_shared,from_n_users,users,n_urls,platform,from,id/url,text,n_likes,n_replies,total,url_id
0,http://chng.it/6FQKFDHkLS,13,1,"(638630549.0,)",{1},instagram,comment,2.455510e+18,@lenynacarrasco http://chng.it/6FQKFDHkLS,2044.0,NaN,2044.0,instagram_comments_dec_0
1,http://chng.it/6FQKFDHkLS,13,1,"(638630549.0,)",{1},instagram,comment,2.455510e+18,@_.pl3tor1co._ http://chng.it/6FQKFDHkLS,705.0,NaN,705.0,instagram_comments_dec_1
2,http://chng.it/cRRfCKcsbm,5,1,"(6768663987.0,)",{1},instagram,comment,2.455510e+18,@samurai_maca http://chng.it/cRRfCKcsbm,537.0,NaN,537.0,instagram_comments_dec_2
3,http://chng.it/6FQKFDHkLS,13,1,"(638630549.0,)",{1},instagram,comment,2.455510e+18,@__senpaaii_ http://chng.it/6FQKFDHkLS,430.0,NaN,430.0,instagram_comments_dec_3
4,http://chng.it/6FQKFDHkLS,13,1,"(638630549.0,)",{1},instagram,comment,2.455510e+18,@elmuerto_inactivo http://chng.it/6FQKFDHkLS,372.0,NaN,372.0,instagram_comments_dec_4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,https://www.change.org/p/walt-disney-we-want-j...,6,1,"(3703701611.0,)",{1},instagram,comment,2.466890e+18,#justiceforjohnnydepp https://www.change.org/p...,3.0,0.0,3.0,instagram_comments_dec_60
65,https://www.change.org/p/dc-entertainment-remo...,26,7,"(30074255940.0, 3703701611.0, 2200653740.0, 56...",{1},instagram,comment,2.455510e+18,@__senpaaii_ https://www.change.org/p/dc-ente...,3.0,NaN,3.0,instagram_comments_dec_62
66,https://www.change.org/p/dc-entertainment-remo...,26,7,"(30074255940.0, 3703701611.0, 2200653740.0, 56...",{1},instagram,comment,2.455510e+18,@__senpaaii_ https://www.change.org/p/dc-ente...,3.0,NaN,3.0,instagram_comments_dec_64
67,https://www.change.org/p/dc-entertainment-remo...,26,7,"(30074255940.0, 3703701611.0, 2200653740.0, 56...",{1},instagram,comment,2.455510e+18,@__senpaaii_ https://www.change.org/p/dc-ente...,3.0,NaN,3.0,instagram_comments_dec_65
68,http://chng.it/DT7NQwK8kG,11,1,"(44298546457.0,)",{1},instagram,comment,2.455510e+18,@bxchxlxcx_2004 http://chng.it/DT7NQwK8kG,3.0,NaN,3.0,instagram_comments_dec_66

In [27]:
top_shared_instagram_dec.to_csv(saving + "top_shared_instagram_dec.csv")

### Top shared instagram across all platforms

In [30]:
shared_dec_instagram_all_platforms = pd.merge(
    shared_dec, top_dec, how="inner"
)
top_shared_instagram_dec = top_shared_instagram_dec.sort_values(
    "total", ascending=False
).reset_index(drop=True)

In [31]:
top_shared_instagram_dec

,shared_url,n_shared,from_n_users,users,n_urls,platform,from,id/url,text,n_likes,n_replies,total,url_id
0,http://chng.it/6FQKFDHkLS,13,1,"(638630549.0,)",{1},instagram,comment,2.455510e+18,@lenynacarrasco http://chng.it/6FQKFDHkLS,2044.0,NaN,2044.0,instagram_comments_dec_0
1,http://chng.it/6FQKFDHkLS,13,1,"(638630549.0,)",{1},instagram,comment,2.455510e+18,@_.pl3tor1co._ http://chng.it/6FQKFDHkLS,705.0,NaN,705.0,instagram_comments_dec_1
2,http://chng.it/cRRfCKcsbm,5,1,"(6768663987.0,)",{1},instagram,comment,2.455510e+18,@samurai_maca http://chng.it/cRRfCKcsbm,537.0,NaN,537.0,instagram_comments_dec_2
3,http://chng.it/6FQKFDHkLS,13,1,"(638630549.0,)",{1},instagram,comment,2.455510e+18,@__senpaaii_ http://chng.it/6FQKFDHkLS,430.0,NaN,430.0,instagram_comments_dec_3
4,http://chng.it/6FQKFDHkLS,13,1,"(638630549.0,)",{1},instagram,comment,2.455510e+18,@elmuerto_inactivo http://chng.it/6FQKFDHkLS,372.0,NaN,372.0,instagram_comments_dec_4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,https://www.change.org/p/walt-disney-we-want-j...,6,1,"(3703701611.0,)",{1},instagram,comment,2.466890e+18,#justiceforjohnnydepp https://www.change.org/p...,3.0,0.0,3.0,instagram_comments_dec_60
65,https://www.change.org/p/dc-entertainment-remo...,26,7,"(30074255940.0, 3703701611.0, 2200653740.0, 56...",{1},instagram,comment,2.455510e+18,@__senpaaii_ https://www.change.org/p/dc-ente...,3.0,NaN,3.0,instagram_comments_dec_64
66,https://www.change.org/p/dc-entertainment-remo...,26,7,"(30074255940.0, 3703701611.0, 2200653740.0, 56...",{1},instagram,comment,2.455510e+18,@__senpaaii_ https://www.change.org/p/dc-ente...,3.0,NaN,3.0,instagram_comments_dec_65
67,http://chng.it/d4wSkC9HZs,12,2,"(37298049714.0, 286371978.0)",{1},instagram,comment,2.455510e+18,@its.matiii._ Link para sacar a amber Heard de...,3.0,NaN,3.0,instagram_comments_dec_68
68,http://chng.it/DT7NQwK8kG,11,1,"(44298546457.0,)",{1},instagram,comment,2.455510e+18,@bxchxlxcx_2004 http://chng.it/DT7NQwK8kG,3.0,NaN,3.0,instagram_comments_dec_66

In [32]:
shared_dec_instagram_all_platforms.to_csv(saving + "shared_dec_instagram_all_platforms.csv")

In [33]:
shared_dec_instagram_all_platforms

,shared_url,n_shared,from_n_users,users,n_urls,platform,from,id/url,text,n_likes,n_replies,total,url_id
0,https://www.change.org/p/dc-entertainment-remo...,1,1,"(948054032,)",{1},change,petition_comment,2.455510e+18,LINK DE LA PETICIÓN 👉 https://www.change.org/p...,9.0,0.0,9.0,instagram_comments_dec_21
1,https://www.change.org/p/dc-entertainment-remo...,1,1,"(948054032,)",{1},change,petition_comment,2.460759e+18,#justiceforjohnnydepp https://www.change.org/p...,5.0,0.0,5.0,instagram_comments_dec_43
2,https://www.change.org/p/dc-entertainment-remo...,1,1,"(948054032,)",{1},change,petition_comment,2.453187e+18,https://www.change.org/p/dc-entertainment-remo...,1.0,4.0,5.0,instagram_comments_dec_44
3,https://www.change.org/p/dc-entertainment-remo...,1,1,"(948054032,)",{1},change,petition_comment,2.455510e+18,@fuckingmaaatrix https://www.change.org/p/dc-e...,4.0,NaN,4.0,instagram_comments_dec_46
4,https://www.change.org/p/dc-entertainment-remo...,1,1,"(948054032,)",{1},change,petition_comment,2.455510e+18,@fuckingmaaatrix https://www.change.org/p/dc-e...,4.0,NaN,4.0,instagram_comments_dec_47
...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,https://www.dailymail.co.uk/tvshowbiz/article-...,1,1,"(531034699.0,)",{1},instagram,comment,2.475209e+18,@blueorchids1 https://www.dailymail.co.uk/tvsh...,23.0,NaN,23.0,instagram_comments_dec_13
165,https://www.dailymail.co.uk/tvshowbiz/article-...,5,5,"(1.29214e+18, 1.11604e+18, 1.30742e+18, 1.1127...",{1},twitter,tweet,2.475209e+18,@blueorchids1 https://www.dailymail.co.uk/tvsh...,23.0,NaN,23.0,instagram_comments_dec_13
166,https://www.dailymail.co.uk/tvshowbiz/article-...,1,1,{303346479.0},{2},twitter,tweet,2.475209e+18,@blueorchids1 https://www.dailymail.co.uk/tvsh...,23.0,NaN,23.0,instagram_comments_dec_13
167,http://chng.it/6mQrjqdMDd,1,1,"(5741972708.0,)",{1},instagram,comment,2.455510e+18,aquí está el link http://chng.it/6mQrjqdMDd,3.0,2.0,5.0,instagram_comments_dec_45
168,https://images.app.goo.gl/iWXssPz56qnNWbiz5,1,1,"(510086034.0,)",{1},instagram,comment,2.462245e+18,@mareeoo10 https://images.app.goo.gl/iWXssPz56...,17.0,NaN,17.0,instagram_comments_dec_17

## Shared on Instagram

In [38]:
top_shared_instagram_4_months[["n_shared", "total"]].corr()

          n_shared     total
n_shared  1.000000 -0.158187
total    -0.158187  1.000000

In [39]:
top_shared_instagram_dec[["n_shared", "total"]].corr()

          n_shared     total
n_shared  1.000000  0.047283
total     0.047283  1.000000

## Shared across all platforms

In [35]:
shared_dec_instagram_all_platforms[["n_shared", "total"]].corr()

          n_shared     total
n_shared  1.000000 -0.027152
total    -0.027152  1.000000

In [36]:
shared_4_months_instagram_all_platforms[["n_shared", "total"]].corr()

          n_shared     total
n_shared  1.000000 -0.072724
total    -0.072724  1.000000