# Top Shared

In [1]:
import pandas as pd

* [4 Months](#4)
    * [Youtube](#y)
    * [Instagram](#ig)
    * [Reddit](#r)
    * [Twitter](#t)
    * [Change](#c)
* [Dec](#dec)

In [2]:
youtube_path =  "../../URLs_Data_Filteration/YouTube/"
instagram_path =  "../../URLs_Data_Filteration/Instagram/"
change_path =  "../../URLs_Data_Filteration/Change/"
reddit_path =  "../../URLs_Data_Filteration/Reddit/"
twitter_path =  "../../URLs_Data_Filteration/Twitter/"

<a id="4"></a>
## 4 Months

<a id="y"></a>
### Youtube

### URLs Data

In [3]:
# youtube links shared on youtube comments 
df_shared_youtube_comments_4_months = pd.concat(
    [
        pd.read_csv(youtube_path + "df_comments_4_months_urls_1_link.csv"),
        pd.read_csv(youtube_path + "df_comments_4_months_urls_more.csv"),
    ]
).sort_values("count", ascending=False)

df_shared_youtube_comments_4_months["platform"] = "youtube"
df_shared_youtube_comments_4_months["from"] = "comment"

In [4]:
df_shared_youtube_comments_4_months.rename(
    columns={
        "link": "shared_link",
        "count": "n_shared",
        "n_users": "from_n_users",
    },
    inplace=True,
)

In [5]:
df_shared_youtube_comments_4_months

,shared_link,n_shared,from_n_users,platform,from
7,https://www.patreon.com/user?u=21542407,24,1,youtube,comment
4,https://www.youtube.com/channel/UCt4dtZ67qO3xW...,24,1,youtube,comment
5,https://www.bitchute.com/channel/a3WbPaAzRKWN/,24,1,youtube,comment
8,https://www.subscribestar.com/nerdettesnewsstand,24,1,youtube,comment
6,https://www.youtube.com/channel/UC8AGq7bm-x4te...,24,1,youtube,comment
...,...,...,...,...,...
296,https://www.therichest.com/world-entertainment...,1,1,youtube,comment
297,https://pagesix.com/2020/11/02/how-johnny-depp...,1,1,youtube,comment
298,https://www.courttv.com/news/amber-heard-witne...,1,1,youtube,comment
299,https://youtu.be/ZUa11ih4abM,1,1,youtube,comment
113,https://www.instagram.com/p/CJEdjaNDQe5/,1,1,youtube,comment

In [6]:
# youtube links shared on youtube videos
df_shared_youtube_videos_4_months = pd.concat(
    [
        pd.read_csv(youtube_path + "df_videos_4_months_urls_1_link.csv"),
        pd.read_csv(youtube_path + "df_videos_4_months_urls_more.csv"),
    ]
).sort_values("count", ascending=False)

df_shared_youtube_videos_4_months["platform"] = "youtube"
df_shared_youtube_videos_4_months["from"] = "comment"

In [7]:
df_shared_youtube_videos_4_months.rename(
    columns={
        "link": "shared_link",
        "count": "n_shared",
        "n_users": "from_n_users",
    },
    inplace=True,
)

In [8]:
df_shared_youtube_videos_4_months

,shared_link,n_shared,from_n_users,platform,from
11,https://support.google.com/youtube/answer/1620...,44,4,youtube,comment
9,https://www.patreon.com/thatumbrellaguy,43,1,youtube,comment
8,https://www.paypal.com/cgi-bin/webscr?cmd=_s-x...,43,1,youtube,comment
1,https://bit.ly/3qF38D7,36,1,youtube,comment
10,https://www.youtube.com/channel/UCbiT0LUIbQj6C...,31,1,youtube,comment
...,...,...,...,...,...
621,https://indyplanet.com/night-knight-1,1,1,youtube,comment
620,https://www.paypal.me/MrNailsin,1,1,youtube,comment
619,https://boundingintocomics.com/2021/02/27/rumo...,1,1,youtube,comment
618,https://www.airy-youtube-downloader.com,1,1,youtube,comment
1438,https://www.youtube.com/channel/UCak7GgON2G8r1...,1,1,youtube,comment

In [9]:
df_shared_youtube = (
    pd.concat([df_shared_youtube_videos_4_months, df_shared_youtube_comments_4_months])
    .sort_values("n_shared", ascending=False)
    .reset_index(drop=True)
)

In [10]:
df_shared_youtube

,shared_link,n_shared,from_n_users,platform,from
0,https://support.google.com/youtube/answer/1620...,44,4,youtube,comment
1,https://www.paypal.com/cgi-bin/webscr?cmd=_s-x...,43,1,youtube,comment
2,https://www.patreon.com/thatumbrellaguy,43,1,youtube,comment
3,https://bit.ly/3qF38D7,36,1,youtube,comment
4,https://www.youtube.com/channel/UCbiT0LUIbQj6C...,31,1,youtube,comment
...,...,...,...,...,...
2290,https://www.standard.co.uk/news/uk/johnny-depp...,1,1,youtube,comment
2291,https://www.etonline.com/news/190049_amber_hea...,1,1,youtube,comment
2292,https://www.rollingstone.com/movies/movie-news...,1,1,youtube,comment
2293,https://www.dailymail.co.uk/news/article-79477...,1,1,youtube,comment
2294,https://www.instagram.com/p/CJEdjaNDQe5/,1,1,youtube,comment

<a id="ig"></a>
### Instagram

In [11]:
df_shared_instagram_comments_4_months = pd.concat(
    [
        pd.read_csv(instagram_path + "df_comments_4_months_urls_1_link.csv"),
        pd.read_csv(instagram_path + "df_comments_4_months_urls_more.csv"),
    ]
).sort_values("count", ascending=False)

df_shared_instagram_comments_4_months["platform"] = "instagram"
df_shared_instagram_comments_4_months["from"] = "comment"

In [12]:
df_shared_instagram_comments_4_months.rename(
    columns={
        "link": "shared_link",
        "count": "n_shared",
        "n_users": "from_n_users",
    },
    inplace=True,
)

In [13]:
df_shared_instagram_comments_4_months

,shared_link,n_shared,from_n_users,platform,from
0,https://youtu.be/uretrfMA-Io,17,8,instagram,comment
174,http://chng.it/9fvfm2mSb4,17,1,instagram,comment
2,www.change.org/p/walt-disney-we-want-johnny-de...,10,2,instagram,comment
143,https://rojakdaily.com/entertainment/article/1...,6,1,instagram,comment
46,https://www.thesun.co.uk/news/uknews/12087519/...,6,1,instagram,comment
...,...,...,...,...,...
81,https://tse2.mm.bing.net/th?id=OGC.6813e006ebd...,1,1,instagram,comment
82,https://youtu.be/wHQHOJQtYTI,1,1,instagram,comment
83,Soundcloud.com/puff-paddy,1,1,instagram,comment
84,https://www.instagram.com/reel/CNCeoMRFkIt/?ig...,1,1,instagram,comment
59,https://youtu.be/jYF392_nfaA,1,1,instagram,comment

<a id="t"></a>
### Twitter

In [14]:
df_shared_twitter_4_months = pd.concat(
    [
        pd.read_csv(twitter_path + "df_tweets_4_months_urls_1_link.csv"),
        pd.read_csv(twitter_path + "df_tweets_4_months_urls_more.csv"),
    ]
).sort_values("count", ascending=False)

In [15]:
df_shared_twitter_4_months["platform"] = "twitter"
df_shared_twitter_4_months["from"] = "tweet"

In [16]:
df_shared_twitter_4_months

                          link  count  n_users platform   from
39787  https://t.co/3m7bqXgJVe    263        1  twitter  tweet
2349   https://t.co/zDMeMo8aX3     82        1  twitter  tweet
2350   https://t.co/UJXgaxsA8C     82        1  twitter  tweet
53605  https://t.co/IGIYBEirli     73        1  twitter  tweet
39477  https://t.co/RnNbphsHbR     70        1  twitter  tweet
...                        ...    ...      ...      ...    ...
21771  https://t.co/sflCUXnZLn      1        1  twitter  tweet
21772  https://t.co/icqNM4ZP7l      1        1  twitter  tweet
21773  https://t.co/LkRksIgcdN      1        1  twitter  tweet
21774  https://t.co/VVr5rWj7WJ      1        1  twitter  tweet
5354   https://t.co/9blqOhqmm7      1        1  twitter  tweet

[64978 rows x 5 columns]

<a id="r"></a>
### Reddit

In [17]:
df_shared_reddit_4_months = pd.concat(
    [
        pd.read_csv(reddit_path + "df_reddits_4_months_urls_1_link.csv"),
        pd.read_csv(reddit_path + "df_reddits_4_months_urls_more.csv"),
    ]
).sort_values("count", ascending=False)

In [18]:
df_shared_reddit_4_months["platform"] = "reddit"
df_shared_reddit_4_months["from"] = "reddits"

In [19]:
df_shared_reddit_4_months.rename(
    columns={
        "link": "shared_link",
        "count": "n_shared",
        "n_users": "from_n_users",
    },
    inplace=True,
)

In [20]:
df_shared_reddit_4_months

,shared_link,n_shared,from_n_users,platform,from
24,https://jerkofftocelebs.com/,139,1,reddit,reddits
25,https://discord.gg/FMhrH2j,139,1,reddit,reddits
22,https://jerkofftocelebs.com/pictures/,128,1,reddit,reddits
21,https://jerkofftocelebs.com/actors/,128,1,reddit,reddits
26,https://jerkofftocelebs.com/reddit-nsfw-list/,128,1,reddit,reddits
...,...,...,...,...,...
90,https://new.reddit.com/r/CelebbattlePolls/comm...,1,1,reddit,reddits
91,https://new.reddit.com/r/CelebbattlePolls/comm...,1,1,reddit,reddits
92,https://new.reddit.com/r/CelebbattlePolls/comm...,1,1,reddit,reddits
39,https://new.reddit.com/r/CelebbattlePolls/comm...,1,1,reddit,reddits
135,https://www.reddit.com/message/compose?to=/r/O...,1,1,reddit,reddits

<a id="c"></a>
### Change

In [21]:
df_shared_change_pcomments_4_months = pd.concat(
    [
        pd.read_csv(change_path + "all_petitions_comments_4_months_urls_1_link.csv"),
        pd.read_csv(change_path + "all_petitions_comments_4_months_urls_more.csv"),
    ]
).sort_values("count", ascending=False)

In [22]:
df_shared_change_pcomments_4_months["platform"] = "change"
df_shared_change_pcomments_4_months["from"] = "petition_comment"

In [23]:
df_shared_change_pcomments_4_months

,link,count,n_users,platform,from
0,https://www.change.org/p/walt-disney-back-john...,6,1,change,petition_comment
1,https://www.change.org/p/me-johnny-depp-as-jac...,3,1,change,petition_comment
0,https://www.change.org/p/%D0%BC%D0%B8%D0%B4-%D...,2,1,change,petition_comment
1,https://www.change.org/p/loma-vista-recordings...,2,1,change,petition_comment
2,https://www.change.org/p/warner-brothers-keep-...,2,1,change,petition_comment
2,https://www.change.org/p/warner-brothers-emili...,1,1,change,petition_comment
3,https://www.change.org/p/all-world-leaders-des...,1,1,change,petition_comment
4,https://www.complaints.judicialconduct.gov.uk/,1,1,change,petition_comment
3,https://www.facebook.com/Delihealth-1014197053...,1,1,change,petition_comment
4,http://www.eximp.com.co/,1,1,change,petition_comment

In [24]:
df_shared_change_pcomments_4_months.rename(
    columns={
        "link": "shared_link",
        "count": "n_shared",
        "n_users": "from_n_users",
    },
    inplace=True,
)

In [25]:
df_shared_change_pcomments_4_months["platform"] = "change"
df_shared_change_pcomments_4_months["from"] = "petition_comment"

In [26]:
df_shared_change_pcomments_4_months

,shared_link,n_shared,from_n_users,platform,from
0,https://www.change.org/p/walt-disney-back-john...,6,1,change,petition_comment
1,https://www.change.org/p/me-johnny-depp-as-jac...,3,1,change,petition_comment
0,https://www.change.org/p/%D0%BC%D0%B8%D0%B4-%D...,2,1,change,petition_comment
1,https://www.change.org/p/loma-vista-recordings...,2,1,change,petition_comment
2,https://www.change.org/p/warner-brothers-keep-...,2,1,change,petition_comment
2,https://www.change.org/p/warner-brothers-emili...,1,1,change,petition_comment
3,https://www.change.org/p/all-world-leaders-des...,1,1,change,petition_comment
4,https://www.complaints.judicialconduct.gov.uk/,1,1,change,petition_comment
3,https://www.facebook.com/Delihealth-1014197053...,1,1,change,petition_comment
4,http://www.eximp.com.co/,1,1,change,petition_comment

## Gather shred Data

In [27]:
df_shared = pd.concat(
    [
        df_shared_change_pcomments_4_months,
        df_shared_instagram_comments_4_months,
        df_shared_reddit_4_months,
        df_shared_youtube,
    ]
)

In [28]:
df_shared

,shared_link,n_shared,from_n_users,platform,from
0,https://www.change.org/p/walt-disney-back-john...,6,1,change,petition_comment
1,https://www.change.org/p/me-johnny-depp-as-jac...,3,1,change,petition_comment
0,https://www.change.org/p/%D0%BC%D0%B8%D0%B4-%D...,2,1,change,petition_comment
1,https://www.change.org/p/loma-vista-recordings...,2,1,change,petition_comment
2,https://www.change.org/p/warner-brothers-keep-...,2,1,change,petition_comment
...,...,...,...,...,...
2290,https://www.standard.co.uk/news/uk/johnny-depp...,1,1,youtube,comment
2291,https://www.etonline.com/news/190049_amber_hea...,1,1,youtube,comment
2292,https://www.rollingstone.com/movies/movie-news...,1,1,youtube,comment
2293,https://www.dailymail.co.uk/news/article-79477...,1,1,youtube,comment
2294,https://www.instagram.com/p/CJEdjaNDQe5/,1,1,youtube,comment

### Top Interacted

In [29]:
youtube_top_path =  "../../Top Interacted/Youtube/Videos_urls/"

In [30]:
df_top_youtube_comments_4_months = pd.read_csv(youtube_top_path + "comments_4_months_top_total.csv")

In [31]:
df_top_youtube_videos_4_months = pd.read_csv(youtube_top_path + "videos_4_months_top_total.csv")

In [32]:
df_top_youtube_comments_4_months

,urls,comment,publish_dtime,n_likes,n_replies,total
0,https://www.youtube.com/watch?v=GWUMe-u9zKE,"No woman should hit a man, just like no man sh...",2021-01-31 15:09:00+00:00,54884.0,487.0,55371.0
1,https://www.youtube.com/watch?v=GWUMe-u9zKE,DisneyÃ¢â‚¬â„¢s got a lot of balls to think people ...,2021-02-01 17:02:16+00:00,46526.0,445.0,46971.0
2,https://www.youtube.com/watch?v=b9V3Pj47x4c,The camera man is the fastest,2021-01-26 01:40:38+00:00,37998.0,495.0,38493.0
3,https://www.youtube.com/watch?v=d4v0E7kkaVQ,"""homosexuals are gay"" im dead",2021-01-10 16:42:30+00:00,23634.0,407.0,24041.0
4,https://www.youtube.com/watch?v=GWUMe-u9zKE,Men are victims too.,2021-02-24 01:39:30+00:00,20738.0,230.0,20968.0
...,...,...,...,...,...,...
882,https://www.youtube.com/watch?v=GWUMe-u9zKE,She is literally the one that mentally and phy...,2021-02-23 07:39:59+00:00,1004.0,2.0,1006.0
883,https://www.youtube.com/watch?v=uretrfMA-Io,"Ã¢â‚¬Å“They wonÃ¢â‚¬â„¢t believe you, because youÃ¢â‚¬â„¢re ...",2021-01-02 03:47:40+00:00,1005.0,0.0,1005.0
884,https://www.youtube.com/watch?v=j_XOf43VV8w,There are way more than 200 accounts because p...,2021-02-04 17:35:19+00:00,996.0,8.0,1004.0
885,https://www.youtube.com/watch?v=f1Gu4oQ0_w4,"""When you're accustomed to privilege equality ...",2021-03-13 02:55:05+00:00,977.0,24.0,1001.0
886,https://www.youtube.com/watch?v=pd-iJRfKPuI,El juez si se hace justicia: Usted seØ£Â±ora Hea...,2021-04-17 03:34:16+00:00,969.0,32.0,1001.0

In [33]:
df_top_youtube_videos_4_months.drop(columns="Unnamed: 0", inplace=True)

In [34]:
df_top_youtube = pd.concat([df_top_youtube_comments_4_months, df_top_youtube_videos_4_months])

In [35]:
df_top_youtube

,urls,comment,publish_dtime,n_likes,n_replies,total,title,n_views,n_dislikes,n_favorites,n_comments
0,https://www.youtube.com/watch?v=GWUMe-u9zKE,"No woman should hit a man, just like no man sh...",2021-01-31 15:09:00+00:00,54884.0,487.0,55371.0,NaN,NaN,NaN,NaN,NaN
1,https://www.youtube.com/watch?v=GWUMe-u9zKE,DisneyÃ¢â‚¬â„¢s got a lot of balls to think people ...,2021-02-01 17:02:16+00:00,46526.0,445.0,46971.0,NaN,NaN,NaN,NaN,NaN
2,https://www.youtube.com/watch?v=b9V3Pj47x4c,The camera man is the fastest,2021-01-26 01:40:38+00:00,37998.0,495.0,38493.0,NaN,NaN,NaN,NaN,NaN
3,https://www.youtube.com/watch?v=d4v0E7kkaVQ,"""homosexuals are gay"" im dead",2021-01-10 16:42:30+00:00,23634.0,407.0,24041.0,NaN,NaN,NaN,NaN,NaN
4,https://www.youtube.com/watch?v=GWUMe-u9zKE,Men are victims too.,2021-02-24 01:39:30+00:00,20738.0,230.0,20968.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
910,https://www.youtube.com/watch?v=t2hma7G6zEI,NaN,NaN,0.0,NaN,2.0,amber heard is addressing the allegations that...,2.0,0.0,0.0,0.0
911,https://www.youtube.com/watch?v=VNpv30MS8Q8,NaN,NaN,0.0,NaN,2.0,solving a rubik's cube everyday until amber he...,2.0,0.0,0.0,0.0
912,https://www.youtube.com/watch?v=KLRBJ6ejt2I,NaN,NaN,0.0,NaN,1.0,you can learn to judge for yourself!! (amber h...,1.0,0.0,0.0,NaN
913,https://www.youtube.com/watch?v=ShGGbAwR9R8,NaN,NaN,0.0,NaN,1.0,#43 || warner bros. screwed up,1.0,0.0,0.0,0.0
914,https://www.youtube.com/watch?v=eC-cByj3fik,NaN,NaN,0.0,NaN,1.0,amber heard allegedly fired from 'aquaman 2' f...,1.0,0.0,0.0,0.0

In [36]:
df_shared

,shared_link,n_shared,from_n_users,platform,from
0,https://www.change.org/p/walt-disney-back-john...,6,1,change,petition_comment
1,https://www.change.org/p/me-johnny-depp-as-jac...,3,1,change,petition_comment
0,https://www.change.org/p/%D0%BC%D0%B8%D0%B4-%D...,2,1,change,petition_comment
1,https://www.change.org/p/loma-vista-recordings...,2,1,change,petition_comment
2,https://www.change.org/p/warner-brothers-keep-...,2,1,change,petition_comment
...,...,...,...,...,...
2290,https://www.standard.co.uk/news/uk/johnny-depp...,1,1,youtube,comment
2291,https://www.etonline.com/news/190049_amber_hea...,1,1,youtube,comment
2292,https://www.rollingstone.com/movies/movie-news...,1,1,youtube,comment
2293,https://www.dailymail.co.uk/news/article-79477...,1,1,youtube,comment
2294,https://www.instagram.com/p/CJEdjaNDQe5/,1,1,youtube,comment

In [37]:
df_top_youtube

,urls,comment,publish_dtime,n_likes,n_replies,total,title,n_views,n_dislikes,n_favorites,n_comments
0,https://www.youtube.com/watch?v=GWUMe-u9zKE,"No woman should hit a man, just like no man sh...",2021-01-31 15:09:00+00:00,54884.0,487.0,55371.0,NaN,NaN,NaN,NaN,NaN
1,https://www.youtube.com/watch?v=GWUMe-u9zKE,DisneyÃ¢â‚¬â„¢s got a lot of balls to think people ...,2021-02-01 17:02:16+00:00,46526.0,445.0,46971.0,NaN,NaN,NaN,NaN,NaN
2,https://www.youtube.com/watch?v=b9V3Pj47x4c,The camera man is the fastest,2021-01-26 01:40:38+00:00,37998.0,495.0,38493.0,NaN,NaN,NaN,NaN,NaN
3,https://www.youtube.com/watch?v=d4v0E7kkaVQ,"""homosexuals are gay"" im dead",2021-01-10 16:42:30+00:00,23634.0,407.0,24041.0,NaN,NaN,NaN,NaN,NaN
4,https://www.youtube.com/watch?v=GWUMe-u9zKE,Men are victims too.,2021-02-24 01:39:30+00:00,20738.0,230.0,20968.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
910,https://www.youtube.com/watch?v=t2hma7G6zEI,NaN,NaN,0.0,NaN,2.0,amber heard is addressing the allegations that...,2.0,0.0,0.0,0.0
911,https://www.youtube.com/watch?v=VNpv30MS8Q8,NaN,NaN,0.0,NaN,2.0,solving a rubik's cube everyday until amber he...,2.0,0.0,0.0,0.0
912,https://www.youtube.com/watch?v=KLRBJ6ejt2I,NaN,NaN,0.0,NaN,1.0,you can learn to judge for yourself!! (amber h...,1.0,0.0,0.0,NaN
913,https://www.youtube.com/watch?v=ShGGbAwR9R8,NaN,NaN,0.0,NaN,1.0,#43 || warner bros. screwed up,1.0,0.0,0.0,0.0
914,https://www.youtube.com/watch?v=eC-cByj3fik,NaN,NaN,0.0,NaN,1.0,amber heard allegedly fired from 'aquaman 2' f...,1.0,0.0,0.0,0.0

In [38]:
df = pd.merge(
    df_shared,
    df_top_youtube,
    left_on="shared_link",
    right_on="urls",
    how="inner"

).drop(columns="urls").sort_values("total", ascending=False)

In [39]:
df

,shared_link,n_shared,from_n_users,platform,from,comment,publish_dtime,n_likes,n_replies,total,title,n_views,n_dislikes,n_favorites,n_comments
214,https://www.youtube.com/watch?v=GWUMe-u9zKE,2,1,youtube,comment,NaN,NaN,191932.0,NaN,4085181.0,"""you saved me"" johnny depp thanks his supporte...",3890345.0,2904.0,0.0,18268.0
245,https://www.youtube.com/watch?v=pZR2_v4UpgI,2,2,youtube,comment,NaN,NaN,40895.0,NaN,1632523.0,amber heardâ€™s lawyer exposes her for ruining j...,1591019.0,609.0,0.0,5487.0
268,https://www.youtube.com/watch?v=bCk2xMs6j8M,2,2,youtube,comment,NaN,NaN,25809.0,NaN,1262704.0,celebrities defending johnny depp against ambe...,1234085.0,2810.0,0.0,2298.0
283,https://www.youtube.com/watch?v=bCk2xMs6j8M,1,1,youtube,comment,NaN,NaN,25809.0,NaN,1262704.0,celebrities defending johnny depp against ambe...,1234085.0,2810.0,0.0,2298.0
387,https://www.youtube.com/watch?v=gECq8x8b6bo,1,1,youtube,comment,NaN,NaN,41871.0,NaN,1099526.0,10 celebrities that defended johnny depp again...,1056676.0,979.0,0.0,3072.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,https://www.youtube.com/watch?v=bCk2xMs6j8M,2,2,youtube,comment,"Johnny Depp is a good humanitarian, he goes an...",2021-03-18 03:56:09+00:00,1003.0,10.0,1013.0,NaN,NaN,NaN,NaN,NaN
282,https://www.youtube.com/watch?v=bCk2xMs6j8M,1,1,youtube,comment,"Johnny Depp is a good humanitarian, he goes an...",2021-03-18 03:56:09+00:00,1003.0,10.0,1013.0,NaN,NaN,NaN,NaN,NaN
213,https://www.youtube.com/watch?v=GWUMe-u9zKE,2,1,youtube,comment,She is literally the one that mentally and phy...,2021-02-23 07:39:59+00:00,1004.0,2.0,1006.0,NaN,NaN,NaN,NaN,NaN
222,https://www.youtube.com/watch?v=j_XOf43VV8w,2,2,youtube,comment,There are way more than 200 accounts because p...,2021-02-04 17:35:19+00:00,996.0,8.0,1004.0,NaN,NaN,NaN,NaN,NaN
343,https://www.youtube.com/watch?v=mrKm6WQeIlY,1,1,youtube,comment,NaN,NaN,20.0,NaN,403.0,amber heard reaction to hollywood officially c...,383.0,0.0,0.0,6.0

In [40]:
df.to_csv("sample.csv", index=False)

In [42]:
df.platform.value_counts()

youtube    437
reddit       1
Name: platform, dtype: int64

In [43]:
df_shared.platform.value_counts()

youtube      2295
reddit        667
instagram     236
change         10
Name: platform, dtype: int64